const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

export interface AICodeRequest {
  description: string;
  contractType?: "token" | "marketplace" | "custom";
  vibeMode?: boolean;
}

export interface AICodeResponse {
  success: boolean;
  code: string;
  error?: string;
}

export interface AIOptimizeRequest {
  code: string;
  optimizationType?: "gas" | "security" | "readability" | "all";
}

export interface VibeSuggestion {
  success: boolean;
  suggestion: string;
}

export async function generateCode(request: AICodeRequest): Promise<AICodeResponse> {
  try {
    const response = await fetch(`${API_URL}/api/ai/generate-code`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        description: request.description,
        contractType: request.contractType || "custom",
        vibeMode: request.vibeMode ?? true,
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error("AI generate code error:", error);
    return {
      success: false,
      code: generateFallbackCode(request.description, request.vibeMode),
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

export async function optimizeCode(request: AIOptimizeRequest): Promise<AICodeResponse> {
  try {
    const response = await fetch(`${API_URL}/api/ai/optimize`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        code: request.code,
        optimizationType: request.optimizationType || "all",
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error("AI optimize error:", error);
    return {
      success: false,
      code: request.code,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

export async function getVibeSuggestion(theme: string): Promise<VibeSuggestion> {
  try {
    const response = await fetch(`${API_URL}/api/ai/vibe-suggestion/${encodeURIComponent(theme)}`);
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error("Vibe suggestion error:", error);
    return {
      success: false,
      suggestion: getDefaultVibeSuggestion(theme),
    };
  }
}

export const VIBE_THEMES = {
  luxury: {
    name: "Luxury Estate",
    colors: ["#D4AF37", "#8B7355", "#F5F5DC", "#1C1C1C"],
    description: "Premium gold accents with elegant serif typography",
  },
  modern: {
    name: "Modern Tech",
    colors: ["#00D4FF", "#7C3AED", "#10B981", "#0F172A"],
    description: "Clean lines, bold colors, futuristic feel",
  },
  playful: {
    name: "Playful Vibes",
    colors: ["#FF6B6B", "#FFE66D", "#4ECDC4", "#FF8E53"],
    description: "Fun colors, bouncy animations, friendly energy",
  },
  nature: {
    name: "Organic Nature",
    colors: ["#2D5016", "#8B4513", "#DEB887", "#F5F5DC"],
    description: "Earth tones, natural textures, calming ambiance",
  },
  dark: {
    name: "Dark Mode",
    colors: ["#6366F1", "#EC4899", "#10B981", "#1F2937"],
    description: "Deep backgrounds, neon accents, tech aesthetic",
  },
} as const;

function getDefaultVibeSuggestion(theme: string): string {
  const normalized = theme.toLowerCase();
  if (normalized.includes("luxury") || normalized.includes("premium")) {
    return VIBE_THEMES.luxury.description;
  }
  if (normalized.includes("modern") || normalized.includes("tech")) {
    return VIBE_THEMES.modern.description;
  }
  if (normalized.includes("playful") || normalized.includes("fun")) {
    return VIBE_THEMES.playful.description;
  }
  if (normalized.includes("nature") || normalized.includes("organic")) {
    return VIBE_THEMES.nature.description;
  }
  if (normalized.includes("dark")) {
    return VIBE_THEMES.dark.description;
  }
  return VIBE_THEMES.modern.description;
}

function generateFallbackCode(description: string, vibeMode?: boolean): string {
  const vibe = vibeMode ? `
  // 🚀 Vibing with code! This is straight fire!
  // Let's build something amazing together!
  // 🔥 Powered by RealFlow Studio AI` : `
  // Generated by RealFlow Studio AI`;

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";${vibe}

/**
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract GeneratedContract is ERC1155, Ownable {
    uint256 private _tokenIdCounter;
    
    constructor() ERC1155("") Ownable(msg.sender) {
        _tokenIdCounter = 0;
    }
    
    function mintRWA(
        address to,
        uint256 amount,
        string memory uri
    ) public onlyOwner returns (uint256) {
        uint256 id = _tokenIdCounter++;
        _mint(to, id, amount, bytes(uri));
        return id;
    }
    
    function mintBatch(
        address to,
        uint256[] memory amounts,
        string[] memory uris
    ) public onlyOwner {
        require(amounts.length == uris.length, "Length mismatch");
        uint256 startId = _tokenIdCounter;
        for (uint256 i = 0; i < amounts.length; i++) {
            _mint(to, startId + i, amounts[i], bytes(uris[i]));
        }
        _tokenIdCounter = startId + amounts.length;
    }
    
    function setURI(uint256 id, string memory newuri) public onlyOwner {
        _setURI(id, newuri);
    }
}
`;
}
