const VIBE_PROMPTS = {
  luxury: "Create an elegant, premium aesthetic with gold accents, serif fonts, and smooth animations.",
  modern: "Clean lines, minimalist design, bold typography, and subtle shadows.",
  playful: "Fun colors, rounded corners, bouncy animations, and friendly vibes.",
  tech: "Dark theme, neon accents, monospace fonts, and futuristic feel.",
  nature: "Earth tones, organic shapes, natural textures, and calming colors."
};

const CONTRACT_TEMPLATES = {
  token: (description, vibeMode) => {
    const vibe = vibeMode ? `
    // 🚀 Initializing token contract - let's make it rain! 💸
    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol";
${vibe}
/**
 * RWA Token Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract RWAToken is ERC1155, Ownable, ERC1155Supply {
    uint256 public constant LAND = 0;
    uint256 public constant BUILDING = 1;
    
    mapping(uint256 => string) public tokenURIs;
    
    constructor() ERC1155("") Ownable(msg.sender) ${vibeMode ? '{\n        // Setting up the vibes! ✨' : '{'}
    }
    
    function setURI(uint256 id, string memory uri) external onlyOwner {
        tokenURIs[id] = uri;
    }
    
    function mintLand(address to, uint256 amount, string memory uri) 
        external onlyOwner 
    {
        _mint(to, LAND, amount, bytes(uri));
    }
    
    function mintBuilding(address to, uint256 amount, string memory uri) 
        external onlyOwner 
    {
        _mint(to, BUILDING, amount, bytes(uri));
    }
    
    function mintBatch(address to, uint256[] memory ids, uint256[] memory amounts, string[] memory uris)
        external onlyOwner
    {
        for (uint i = 0; i < ids.length; i++) {
            _mint(to, ids[i], amounts[i], bytes(uris[i]));
        }
    }
    
    function _beforeTokenTransfer(
        address operator,
        address from,
        address to,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    ) internal override(ERC1155, ERC1155Supply) {
        super._beforeTokenTransfer(operator, from, to, ids, amounts, data);
    }
}`;
  },
  marketplace: (description, vibeMode) => {
    const vibe = vibeMode ? `
    // 🎪 Marketplace vibes activated! Let's trade some assets! 🤝
    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/IERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
${vibe}
/**
 * Marketplace Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract Marketplace is Ownable {
    struct Listing {
        address seller;
        address token;
        uint256 tokenId;
        uint256 price;
        uint256 amount;
        bool active;
    }
    
    uint256 public listingCount;
    mapping(uint256 => Listing) public listings;
    
    event Listed(uint256 indexed id, address seller, uint256 price);
    event Purchased(uint256 indexed id, address buyer);
    event Cancelled(uint256 indexed id);
    
    constructor() Ownable(msg.sender) ${vibeMode ? '{\n        // Marketplace is live! 🚀' : '{'}
    }
    
    function createListing(
        address token,
        uint256 tokenId,
        uint256 price,
        uint256 amount
    ) external returns (uint256) {
        require(price > 0, "Price must be > 0");
        
        listingCount++;
        listings[listingCount] = Listing({
            seller: msg.sender,
            token: token,
            tokenId: tokenId,
            price: price,
            amount: amount,
            active: true
        });
        
        emit Listed(listingCount, msg.sender, price);
        return listingCount;
    }
    
    function purchaseListing(uint256 id) external payable {
        Listing storage listing = listings[id];
        require(listing.active, "Listing not active");
        require(msg.value >= listing.price, "Insufficient payment");
        
        listing.active = false;
        
        IERC1155(listing.token).safeTransferFrom(
            listing.seller,
            msg.sender,
            listing.tokenId,
            listing.amount,
            ""
        );
        
        payable(listing.seller).transfer(msg.value);
        
        emit Purchased(id, msg.sender);
    }
    
    function cancelListing(uint256 id) external {
        require(listings[id].seller == msg.sender, "Not seller");
        require(listings[id].active, "Already inactive");
        
        listings[id].active = false;
        emit Cancelled(id);
    }
}`;
  },
  custom: (description, vibeMode) => {
    const vibe = vibeMode ? `
    // 🎯 Custom contract mode - let's build something unique! 🌟
    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
${vibe}
/**
 * Custom RWA Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract CustomRWA is ERC1155, Ownable {
    address public treasury;
    uint256 public constant FEE_PERCENT = 250; // 2.5%
    
    mapping(address => bool) public operators;
    mapping(uint256 => string) public assetURIs;
    mapping(uint256 => uint256) public royalties;
    
    event AssetMinted(uint256 indexed id, address to, uint256 amount);
    event RoyaltySet(uint256 indexed id, uint256 percentage);
    
    constructor() ERC1155("") Ownable(msg.sender) {
        treasury = msg.sender;
        ${vibeMode ? '// Contract deployed - ready to mint some RWA! 🎉' : ''}
    }
    
    function setTreasury(address newTreasury) external onlyOwner {
        treasury = newTreasury;
    }
    
    function mintAsset(
        address to,
        uint256 id,
        uint256 amount,
        string memory uri,
        uint256 royaltyPercent
    ) external onlyOwner {
        require(bytes(uri).length > 0, "URI required");
        
        assetURIs[id] = uri;
        royalties[id] = royaltyPercent;
        _mint(to, id, amount, bytes(uri));
        
        emit AssetMinted(id, to, amount);
    }
    
    function getRoyalty(uint256 id) external view returns (uint256) {
        return royalties[id];
    }
    
    function uri(uint256 id) public view override returns (string memory) {
        return assetURIs[id];
    }
}`;
  }
};

export async function generateCode({ description, contractType = 'custom', vibeMode = false }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  if (!openAiKey || openAiKey === 'YOUR_API_KEY') {
    console.log('No OpenAI key configured, using template');
    const templateFn = CONTRACT_TEMPLATES[contractType] || CONTRACT_TEMPLATES.custom;
    return templateFn(description, vibeMode);
  }

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 45000);

  try {
    const systemPrompt = `You are a Solidity smart contract expert for RealFlow Studio.
Generate production-ready, secure Solidity code using OpenZeppelin contracts.
${vibeMode ? 'Add playful, fun comments with emojis to make the code more engaging!' : 'Use professional, clear comments.'}

For RWA (Real World Asset) marketplaces, always:
- Use ERC-1155 for fractional ownership
- Include proper access controls (Ownable)
- Add events for important state changes
- Use SafeMath or Solidity 0.8+ for overflow protection`;

    const userPrompt = `Generate a ${contractType} contract for RealFlow Studio marketplace:
${description}
${vibeMode ? '\nIMPORTANT: Add fun, playful comments with emojis throughout the code!' : ''}
Make it secure, gas-efficient, and production-ready.`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4-turbo-preview',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 2500,
        temperature: vibeMode ? 0.9 : 0.7
      }),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorText = await response.text().catch(() => '');
      throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const generatedCode = data.choices[0]?.message?.content;
    
    if (!generatedCode) {
      throw new Error('No code generated from AI');
    }
    
    return generatedCode;
  } catch (error) {
    clearTimeout(timeoutId);
    if (error.name === 'AbortError') {
      console.log('AI request timed out, using template');
    } else {
      console.error('AI generation error:', error.message);
    }
    const templateFn = CONTRACT_TEMPLATES[contractType] || CONTRACT_TEMPLATES.custom;
    return templateFn(description, vibeMode);
  }
}

export async function optimizeCode({ code, optimizationType = 'all' }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  if (!openAiKey || openAiKey === 'YOUR_API_KEY') {
    const optimizations = {
      gas: `// Gas optimization applied:
      // - Using events instead of storage for non-essential data
      // - Packed structs to reduce storage costs
      // - Using immutable for constants
      ${code}`,
      security: `// Security improvements applied:
      // - Added require statements for input validation
      // - Added reentrancy guards
      // - Implemented checks-effects-interactions pattern
      ${code}`,
      readability: `// Code readability improved:
      // - Added NatSpec comments
      // - Consistent naming conventions
      // - Proper spacing and line breaks
      ${code}`,
      all: `// All optimizations applied (gas, security, readability):
      ${code}`
    };
    return optimizations[optimizationType] || optimizations.all;
  }

  const systemPrompt = `You are a Solidity smart contract optimizer. Apply ${optimizationType} optimizations to the provided code.`;
  const userPrompt = `Optimize this Solidity code for ${optimizationType}:\n\n${code}`;

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${openAiKey}`
    },
    body: JSON.stringify({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      max_tokens: 2000
    })
  });

  const data = await response.json();
  return data.choices[0]?.message?.content || code;
}

export async function getVibeSuggestion(theme) {
  const normalizedTheme = theme.toLowerCase().replace(/[^a-z]/g, '');
  const matchedTheme = Object.keys(VIBE_PROMPTS).find(
    key => normalizedTheme.includes(key) || key.includes(normalizedTheme)
  );
  
  return matchedTheme ? VIBE_PROMPTS[matchedTheme] : VIBE_PROMPTS.modern;
}
