const VIBE_PROMPTS = {
  luxury: "Create an elegant, premium aesthetic with gold accents, serif fonts, and smooth animations.",
  modern: "Clean lines, minimalist design, bold typography, and subtle shadows.",
  playful: "Fun colors, rounded corners, bouncy animations, and friendly vibes.",
  tech: "Dark theme, neon accents, monospace fonts, and futuristic feel.",
  nature: "Earth tones, organic shapes, natural textures, and calming colors."
};

export async function generateCode({ description, contractType = 'custom', vibeMode = false }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  if (!openAiKey) {
    return generateMockCode(description, contractType, vibeMode);
  }

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 second timeout

  try {
    const contractTemplates = {
      token: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract GeneratedToken {
    // Token implementation
}`,
      marketplace: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract GeneratedMarketplace {
    // Marketplace implementation
}`,
      custom: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract CustomContract {
    // Custom implementation
}`
    };

    const vibeComment = vibeMode ? 
      "\n    // This code is straight fire! 🔥 Let the vibes flow! \n" : "";

    const systemPrompt = `You are a Solidity smart contract expert for RealFlow Studio.
Generate secure, optimized Solidity code. Add fun comments in vibe mode.`;

    const userPrompt = `${vibeComment}Generate a ${contractType} contract for: ${description}
${vibeMode ? "Include playful comments like '// Vibing with gas savings!'" : ""}`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 2000,
        temperature: 0.7
      }),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      throw new Error('AI service unavailable');
    }

    const data = await response.json();
    return data.choices[0]?.message?.content || contractTemplates[contractType];
  } catch (error) {
    clearTimeout(timeoutId);
    if (error.name === 'AbortError') {
      throw new Error('AI request timed out');
    }
    console.error('AI generation error:', error);
    return generateMockCode(description, contractType, vibeMode);
  }
}

export async function optimizeCode({ code, optimizationType = 'all' }) {
  const optimizations = {
    gas: 'Optimize for gas efficiency: use events for storage, minimize SLOADs.',
    security: 'Add security checks: require statements, reentrancy guards, overflow protection.',
    readability: 'Add clear comments, consistent naming, proper spacing.',
    all: 'Apply all optimizations for gas, security, and readability.'
  };

  return `
// Original: ${optimizations[optimizationType]}
// Optimized version of your code would be generated here
${code}
`;
}

export async function getVibeSuggestion(theme) {
  const normalizedTheme = theme.toLowerCase().replace(/[^a-z]/g, '');
  const matchedTheme = Object.keys(VIBE_PROMPTS).find(
    key => normalizedTheme.includes(key) || key.includes(normalizedTheme)
  );
  
  return matchedTheme ? VIBE_PROMPTS[matchedTheme] : VIBE_PROMPTS.modern;
}

function generateMockCode(description, contractType, vibeMode) {
  const vibe = vibeMode ? `
  // Yo! This code is vibing! 🚀
  // Let's make some blockchain magic happen!
  ` : '';

  const baseCode = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

${vibe}
/**
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract GeneratedContract {
    address public owner;
    
    constructor() {
        owner = msg.sender;
    }
    
    modifier onlyOwner() {
        require(msg.sender == owner, "Not the owner!");
        _;
    }
}`;

  return baseCode;
}
